pipeline:
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  build:
    image: scalacenter/scala:1.0
    pull: true
    commands:
      - sbt clean test sbt-rewrites-plugin/scripted
      - cd scalafix && sbt tests/test

  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
